
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjMzMzMzNDUz","is_bot":false,"login":"a-k-u-m-a-r","name":"Akshay Kumar"},"headRefName":"AK-RecommendationRequest-Placeholder","number":89,"title":"AK: Implement Placeholder pages for RecommendationRequests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/89"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-copy-placeholder-pages","number":88,"title":"mj - created placeholder page for menuitemreview and tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/88"},{"author":{"id":"MDQ6VXNlcjMzMzMzNDUz","is_bot":false,"login":"a-k-u-m-a-r","name":"Akshay Kumar"},"headRefName":"AK-RecommendationRequest-Table","number":87,"title":"AK - Implement Tables and Tests ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/87"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-form-component","number":82,"title":"Mike form component for issue #37","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/82"}]
