
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQyOTg1Njg3","is_bot":false,"login":"ericpretzel","name":"Eric W"},"headRefName":"Eric-HelpRequestBackend","number":70,"title":"Backend for HelpRequest","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/70"},{"author":{"id":"MDQ6VXNlcjQyOTg1Njg3","is_bot":false,"login":"ericpretzel","name":"Eric W"},"headRefName":"Eric-HelpRequestFixtures","number":69,"title":"Add helpRequestFixtures.js","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/69"},{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"TC-Articles-backend","number":68,"title":"Copied article files from team02 to team03","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/68"}]
