
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinL-CopyBackendFiles","number":77,"title":"copied all files for UCSB Organization","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/77"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-menuitemreviewfixture","number":76,"title":"mj - added menuitemreviewfixtures.js file","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/76"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-issue36","number":75,"title":"mj - copied files over: copied over files","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/75"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-readmetable","number":74,"title":"mj - added readme table","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/74"}]
