
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNjY4MzI3","is_bot":false,"login":"KevinChen0527","name":"Kevin Chen"},"headRefName":"KevinC-TableUCSBDiningCommonsMenuItem","number":109,"title":"UCSB Dining commons menu Item form","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/109"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-edit","number":108,"title":"mj reverted backend changes","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/108"},{"author":{"id":"MDQ6VXNlcjYxNjY4MzI3","is_bot":false,"login":"KevinChen0527","name":"Kevin Chen"},"headRefName":"KevinC-FixtureUCSBDiningCommonsMenuItem","number":107,"title":"UCSB Dining Commons Menu Item Form Component","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/107"}]
