
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinLavelle-Homework5","number":122,"title":"Kevin Lavelle UCSB Organization - Integration and End to End Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/122"},{"author":{"id":"MDQ6VXNlcjMzMzMzNDUz","is_bot":false,"login":"a-k-u-m-a-r","name":"Akshay Kumar"},"headRefName":"AK-IntEndTest","number":121,"title":"RecommendationRequests - Implement Integration and EndToEnd Tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/121"}]
