
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinL-TableComponent","number":98,"title":"Kevin L Table component UCSB Organizations","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/98"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"KevinL-CreatePageUCSBOrganization","number":97,"title":"Create Page for UCSBOrganization and refactoring of variable names","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/97"},{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"TC-Articles-Pages","number":96,"title":"Articles page added to App.js","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/96"},{"author":{"id":"MDQ6VXNlcjkxMzQyOTk2","is_bot":false,"login":"MeDotE","name":"Mike Jiang"},"headRefName":"mike-create-page","number":94,"title":"Mike create page","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-3/pull/94"}]
